"""Application-wide defaults."""

DEFAULT_PARENT_CHUNK_SIZE = 600
DEFAULT_PARENT_CHUNK_OVERLAP = 60
DEFAULT_CHILD_CHUNK_SIZE = 200
DEFAULT_CHILD_CHUNK_OVERLAP = 20
DEFAULT_RETRIEVAL_TOP_K = 10
DEFAULT_RETRIEVAL_CANDIDATE_K = 50
HNSW_M = 16
HNSW_EF = 100
